export const FETCH_CURRENT_USER_REQUEST = 'user/FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'user/FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'user/FETCH_CURRENT_USER_FAILURE';

export const LOGIN_REQUEST = 'user/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'user/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'user/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'user/LOGOUT_FAILURE';

export const REGISTER_USER_REQUEST = 'user/REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'user/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'user/REGISTER_USER_FAILURE';